### PR TITLE
Add Default Values to Form Fields

### LINKED ISSUE #191: Be able to specify a default value for form controls
__Is your feature request related to a problem? Please describe__

In some cases users would want to specify default values for a form in the form schema so that the value automatically ends up in the submission result. This is not the case at the moment and be unexpected for users (cf. https://github.com/bpmn-io/form-js/issues/190).

__Describe the solution you'd like__

* [x] As a user I am able to specify default values for input fields via the editor
* [x] The default value is serialized as `defaultValue` in a form item definition
* [x] In the absence of input data provided to the form default values are used to pre-fill the form
* [x] On submission default values are submitted like dirty fields

__Describe alternatives you've considered__

Keep things as is. If a user requires a default value for an input she must input that one via data into the form.

__Additional context__

Related to https://github.com/bpmn-io/form-js/issues/190

### PR DESCRIPTION
**Pull request by philippfromme**
### Changes

* form fields have optional `defaultValue` property
* default value will be used during import if no value is set
* value can be changed after import
* default value can be set through properties panel

### Viewer

Default value is `Max Mustermann GmbH`. Resetting form resets form field to default value.

Vv8tEH9eDw

### Editor

Default value can be set through properties panel.

muTvgPghww

---

Closes #191

### CODE REVIEW

**Review by nikku — CHANGES_REQUESTED** [review]
Feedback UX-wise, I did not give it a through technical look:

* Consider showing the default value in the input preview in the editor; this gives the user a very quick way to determine that it has been set (we also display `*` if a form is required). If we go this route we shall show it everywhere, consistently (i.e. on radios, selects, ... too).
    image

* Do not offer an undefined default value for check-boxes. They shall either be _false_ or _true_ => As a user I cannot distinguish false from _not set_. Default to `false`.
    image

----

Overall it really works like a charm (which can be easily verified using the form-js playground):


```
npm install && npm run start:playground
```

---

Great great great job :clap:.

**Comment by philippfromme** [comment]
@nikku Valid points, I will address them. 💪🏻

**Comment by philippfromme** [comment]
Follow-up issue: https://github.com/bpmn-io/form-js/issues/215

**Review by nikku — APPROVED** [review]
Works like a charm.

**Comment by philippfromme** [comment]
🎉

**Pull request merged**
