### PR TITLE
Document and test <changed> event

### PR DESCRIPTION
**Pull request by nikku**
This makes the `changed` event in the viewer available as an API for integrators to hook into.

---

Closes https://github.com/bpmn-io/form-js/issues/16.

### CODE REVIEW

**Review by philippfromme — APPROVED** [review]
We could think about simplifying `dataPath` to `path` for the publically accessible `update` method. In the form viewer, the path always refers to the data path. In the form editor, the path of the public methods (e.g. `addField`, `moveField`) will always refer to the schema path.

This PR is 💅

**Comment by nikku** [comment]
`#update` is not part of the public, documented API yet. So we're free to adjust things at will.

**Comment by nikku** [comment]
Thx for review. I'll cut a new release.

**Comment by nikku** [comment]
I just realized that we called it `dataPath` internally. But honestly, I think that one will remain an internal API. And for these internal uses, `dataPath` is just fine, too.

**Comment by philippfromme** [comment]
Okay, makes sense to keep it internal. Let's rename the method to `_update` then.

**Pull request merged**
