### PR TITLE
feat(editor): improve dynamic input field description

### PR DESCRIPTION
**Pull request by smbea**
Related to #303

image

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
For transparency (why this is still in draft): We are lacking support in `properties-panel` to properly display `code` elements in descriptions.

Context: https://github.com/bpmn-io/form-js/pull/315#discussion_r950004707

**Comment by pinussilvestrus** [comment]
I went on simply adding the missing parts via https://github.com/bpmn-io/properties-panel/pull/219. @christian-konrad @RomanKostka feel free to share your feedback; I did not modify anything specific to the existing properties panel styles.

image

**Comment by nikku** [comment]
Not exactly sure why this is necessary at the core. You can always override stuff, and once you feel it is a mature solution (for a given context) _then_ we could ship a solution at the core. 

But either way awesome that you pick up this low hanging fruit @pinussilvestrus :medal_sports: .

**Comment by christian-konrad** [comment]
@pinussilvestrus I also created this small PR https://github.com/bpmn-io/form-js/pull/543, so probably we should adjust the message

**Comment by pinussilvestrus** [comment]
> @pinussilvestrus I also created this small PR #543, so probably we should adjust the message

We can adjust the message once we settle on something in the context of #543. This should not block us here.

**Comment by pinussilvestrus** [comment]
This is ready for review now.

**Review by vsgoulart — COMMENTED** [review]
Found this issue we discussed through Slack
it seems to not be happening on `develop`, so it could potentially be some CSS leaking from the properties panel update

image

**Review by vsgoulart — COMMENTED** [review]
It seems to be working well, but I think the validation is not ideal.
If I add a value like `[{"label": "bar", "value": "foo"}]` it complains because of the spaces even though it's a valid value. It's specially confusing since if you just copy and paste the value from the description it shows an error

Maybe we should use a [function](https://github.com/camunda/tasklist/blob/master/client/src/modules/utils/isValidJSON.tsx) like Tasklist to valid this JSON array?

**Comment by pinussilvestrus** [comment]
Where did you paste the JSON? Note that the "Input values key" only accepts a variable name, and that variable needs to follow this structure, not the key.

image

Should we update the description to make that clearer? /cc @RomanKostka @christian-konrad

**Comment by vsgoulart** [comment]
> Where did you paste the JSON? Note that the "Input values key" only accepts a variable name, and that variable needs to follow this structure, not the key.
> 
> image
> 
> Should we update the description to make that clearer? /cc @RomanKostka @christian-konrad

Ah, ok. I misinterpreted it :sweat_smile:

**Review by vsgoulart — APPROVED** [review]
I think  changing the label would be better, but if you think it's not necessary the rest looks ok to me

**Comment by pinussilvestrus** [comment]
Thanks for the review! I'd let it open for @christian-konrad and @RomanKostka whether we want to further improve the description + labels.

**Review by RomanKostka — APPROVED** [review]
nice!
> I think changing the label would be better, but if you think it's not necessary the rest looks ok to me
i agree and would also vote for the singular label.
Besides that it looks fine for me

**Comment by pinussilvestrus** [comment]
Regarding the label: Personally I'd still be in favor of the plural. You are defining *options* with the key, not a *single value*.

**Pull request merged**
