### PR TITLE
Migrate Properties Panel to latest framework version

### LINKED ISSUE #249: Migrate to common bpmn-io properties panel
__Is your feature request related to a problem? Please describe__

The form-js properties panel is custom, hence it differs technically and from UI to the "common" bpmn-io properties panel.

__Describe the solution you'd like__

Migrate to https://github.com/bpmn-io/properties-panel for the properties panel

* [x] Decide about integration strategy
  * [x] Integrate [properties panel framework](https://github.com/bpmn-io/properties-panel) as component, or
  * [x] Provide properties panel as form-js extension
* [x] Add [header provider](https://github.com/bpmn-io/properties-panel/blob/main/src/components/Header.js)
* [x] Migrate groups
  * [x] general
    * [x] id: text  
    * [x] label: text  
    * [x] description: text  
    * [x] key: text  
    * [x] defaultValue: select or number or text  
    * [x] action: select  
    * [x] columns: number  
    * [x] text: textArea  
    * [x] disabled: checkbox  
  * [x] values
    * [x] add as list group (can be group + nested list in the future) 
    * [x] label: text
    * [x] value: text
  * [x] validation
    * [x] required: checkbox  
    * [x] minLength: number  
    * [x] maxLength: number  
    * [x] pattern: text  
  * [x] custom properties
    * [x] add as list group
    * [x] key: text
    * [x] value: text
* [x] Migrate tests 
* [x] Migrate labels to sentence case (to be in line with bpmn- and dmn- propPanel)
* [x] Provide placeholders (although not supported by now), cf. https://github.com/bpmn-io/properties-panel/pull/152
* [x] Consider: override variables inside Camunda Modeler to provide a higher contrast
  * `--color-properties-container-background`
  * `--color-properties-input-background` 

__Describe alternatives you've considered__

Keep existing infrastructure.

__Additional context__

* Analog to solutions for
  * bpmn: https://github.com/bpmn-io/bpmn-js-properties-panel
  * dmn: https://github.com/bpmn-io/dmn-js-properties-panel

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #249 

Screenshot of the new Forms Properties Panel

* [x] Integrate `@bpmn-io/properties-panel` framework
* [x] Migrate entries
* [x] Migrate test coverage
* [x] Remove old components (or do it later? breaking change?) 
  * [x] Remove preact components
  * [x] Remove styles
* [x] Consider: Have the properties panel as an own (feature) module (as we have in BPMN and DMN)
  * => proposal: Do not do it now, as it does not add any value to the migration itself. Personally, I like that everything just lives under the same tree, and I do not have to handle around different containers. If we do so, we should handle it in an orderly manner (also considering the Palette) (cf. https://github.com/bpmn-io/form-js/pull/254#issuecomment-1142083791)
  * ==> that might change though (cf. https://github.com/bpmn-io/form-js/pull/254#issuecomment-1135829669)
* [x] Resolve preact dependency (`src/components` vs. bundled components) (cf. https://github.com/bpmn-io/form-js/pull/254#issuecomment-1126029632)

To try out:

a) Playground

```sh
npx @bpmn-io/sr bpmn-io/form-js#249-migrate-properties-panel -c "npm run start:playground" --verbose
```

b) Camunda Modeler (artifacts)
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/update-forms-properties-panel/camunda-modeler-update-forms-properties-panel-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/update-forms-properties-panel/camunda-modeler-update-forms-properties-panel-mac.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/update-forms-properties-panel/camunda-modeler-update-forms-properties-panel-mac.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/update-forms-properties-panel/camunda-modeler-update-forms-properties-panel-win-ia32.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/update-forms-properties-panel/camunda-modeler-update-forms-properties-panel-win-x64.zip

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
I still receive preact version mismatch errors when using the `@bpmn-io/properties-panel` distros and using them inside the form editor. I [added the dependency as peer](https://github.com/bpmn-io/form-js/pull/254/files#diff-f285967735af435cfb962418c7e2059db93e7a9310b6f09f4950d12c36682425R56) to the `form-js-editor` and simply importing the components I need.

```js
import { 
  PropertiesPanel,
  TextFieldEntry,
  ... 
} from '@bpmn-io/properties-panel';
```

And then `npm run start:editor`.

```text
index.jss?fbd0:110 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__H')
    at m (index.jss?fbd0:110:3)
    at p (index.jss?fbd0:138:8)
    at l (index.jss?fbd0:126:16)
    at _.PropertiesPanel [as constructor] (PropertiesPanel.jss?d3c9:114:41)
    at _.O [as render] (index.jss?5962:513:14)
    at j (index.jss?5962:181:12)
    at w (children.jss?36d0:137:3)
    at L (index.jss?5962:404:4)
    at j (index.jss?5962:232:20)
    at w (children.jss?36d0:137:3)
```

The only way I get it working currently is to use the `src/components` and [dedup the `preact` dependency](https://github.com/bpmn-io/form-js/pull/254/files#diff-c46d714a3255dafee187ec87329d9b014e49532ce1a6dd9e1294fd0a98330b45R101) (as in good old properties panel times). This can't be used in production as we do not expose these components. It's also not our planned usage scenario.

```js
import PropertiesPanel from '@bpmn-io/properties-panel/src/PropertiesPanel';

import { TextFieldEntry } from '@bpmn-io/properties-panel/src/components';
```

You can find more details in the code changes. Is there anything I'm missing above?

/cc @barmac @nikku @philippfromme

**Comment by pinussilvestrus** [comment]
> Consider: Have the properties panel as an own (feature) module (as we have in BPMN and DMN)

This could probably fix this problem as we would simply use `@bpmn-io/properties-panel/preact` for this micro-frontend. However, I wonder whether this would be an overhead for this particular task.

**Comment by nikku** [comment]
@pinussilvestrus Do you already know when the issue happens and why?

Generally speaking due to the nature how Preact (and React) handle global state there must only be one instance of it at work in an apps component tree.

It is not sufficient to use some Preact in the editor, we must use it everywhere in form-js (as the editor also re-uses parts of the viewer). Let us make this a dedicated point to discuss in sync. Your pain is exactly the pain any integrator suffers. First step is to understand the problem space as a team, second step is to discuss dedicated paths forward.

**Comment by pinussilvestrus** [comment]
I updated the PR to be prepared to be reviewed once we clarified how to deal with preact: https://github.com/bpmn-io/form-js/pull/254#issuecomment-1126054064

I removed all the old properties panel components as they are no longer used. I wouldn't consider this a breaking change as we anyway don't export them.

**Comment by pinussilvestrus** [comment]
What I'm wondering alongside the preact discussion (just writing it down here so we have it tracked): Why don't we support both?

* Export properties-panel preact version under `@bpmn-io/properties-panel/dist/preact` so integrators (e.g. `bpmn-js-properties-panel`, extensions) can use it. Then I have to use the components exposed via `@bpmn-io/properties-panel/dist/` I don't have to care about the preact version.
* Also export the bare components via `@bpmn-io/properties-panel/src`. Then integrators can decide on their preact version and bundle it themselves + dedup if necessary, as this PR is currently doing it.

**Comment by pinussilvestrus** [comment]
> * [Replace the `preact` aliasing](https://unpkg.com/browse/@bpmn-io/properties-panel@0.14.0/dist/index.esm.js) we have in the distros to use the `preact` version defined via form-js

I sketched this via f9c83529826b0aaf4a1e56695b9386f209f929b4. Feels hacky but would just work 🐒 

```
npx @bpmn-io/sr bpmn-io/form-js#249-migrate-properties-panel -c "npm run start:editor" --verbose
```

**Comment by pinussilvestrus** [comment]
I now solved it via handling the `@bpmn-io/properties-panel` dependency similar to we handle `diagram-js` (cf. [rollup config](https://github.com/bpmn-io/form-js/pull/254/files#diff-f707332fc59bc6e06edf342a7ba3dd190a7e6d493d33c0c77b64bc7e8104b145)). That might not work if we start to allow extensions for form-js, but solves the preact versioning error for now.

What I will do before sending this PR under review is to try out the second approach

> Keep the properties panel outside the editor and add via own micro-frontend, using the provided properties panel preact version (as this is how it is designed)

... to get a feeling whether that would be the better approach to go.

**Comment by pinussilvestrus** [comment]
I created artifacts for the migration together with the Camunda Modeler. Please find them in the PR description above 👍. This ready for review now. 

image

**Comment by marstamm** [comment]
Compared with the 5.0.0 modeler, the created schema has `validate.pattern` instead of `validate.regularExpressionPattern`. Did we decide to change it or is this caused by this PR?

**Comment by marstamm** [comment]
Never mind, it is expected and was changed here: https://github.com/bpmn-io/form-js/pull/245

**Review by marstamm — APPROVED** [review]
Great to have the properties panels aligned :rocket:

**Comment by pinussilvestrus** [comment]
Thanks for review @marstamm 👍 I have to rebase the properties panel on top of the new Taglist component, and will merge afterward 🙂

**Pull request merged**
