### PR TITLE
Integrate `@bpmn-io/draggle`

### PR DESCRIPTION
**Pull request by pinussilvestrus**
This uses an updated `dragula` version to make the `direction` dynamic. It detects whether the drop would happen inside a row or not and change the direction accordingly.

This makes drag & drop quite a bit smoother as it uses the correct axis depending where the cursor is located. Beforehand it would always have used the y-axis. 

Depends on https://github.com/bpmn-io/dragula/pull/1

Demo: https://demo-improve-dragging--camunda-form-playground.netlify.app/

Kapture 2023-03-30 at 13 59 19

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Note that we likely need a fork for customizations, as the [`dragula`](https://github.com/bevacqua/dragula) project is pretty much not maintained at the moment. That might change once [dragula@2](https://github.com/toofff/dragula2/issues/2) comes to live, but there is no timeline for this.

**Comment by toofff** [comment]
Hi :wave: 

For the moment I don't have a release date for Dragula2 but I will have a little more time this month to finalize part of my roadmap. If an alpha is possible, I'll let you know if you like?

For information, I started this redesign project because I also wanted to have an official integration of the "drag cursor position offset" functionality.

**Comment by pinussilvestrus** [comment]
Hi @toofff, thanks for reaching out! We'd love to try out your alpha version once its available 🚀 The position offset is actually something we would like to use, as we [identified it already while integrating `dragula`](https://github.com/bpmn-io/form-js/blob/develop/packages/form-js-editor/src/render/components/FormEditor.js#L466).

Let's stay in contact 👍

**Comment by pinussilvestrus** [comment]
An evidence why we should have a look at this PR, soo : https://github.com/bpmn-io/form-js/pull/591#issuecomment-1496258439

**Comment by pinussilvestrus** [comment]
This is ready for review now 🎉

**Review by Skaiir — APPROVED** [review]

**Review by RomanKostka — APPROVED** [review]
looks good from my side - very smoothly!

**Pull request merged**
