### PR TITLE
docs: add notes about `getSchemaVariables`

### LINKED ISSUE #729: Document `getSchemaVariables`
### What should we do?

We should write up some docs for getSchemaVariables somewhere, perhaps in the usage section, to inform how it should be used. 

### Why should we do it?

See: https://github.com/bpmn-io/form-js/pull/611#discussion_r1266772124

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #729

### CODE REVIEW

**Comment by vsgoulart** [comment]
@pinussilvestrus I think the Carbon custom styles migration to SCSS is unrelated to this PR, no?

**Comment by pinussilvestrus** [comment]
Oh damn, forgot to switch the branches 🐒

**Review by vsgoulart — COMMENTED** [review]
The docs look good to me, but you think it makes sense to add some version of this example in the JSDoc annotation of `getSchemaVariables`?

**Review by vsgoulart — APPROVED** [review]

**Comment by pinussilvestrus** [comment]
> The docs look good to me, but you think it makes sense to add some version of this example in the JSDoc annotation of `getSchemaVariables`?

Good catch! The JSDocs were anyway fairly outdated. I updated them and added some `@example` tags.

**Review by Skaiir — APPROVED** [review]
Lovely :)

**Pull request merged**
