### PR TITLE
fix: correct form icon

### PR DESCRIPTION
**Pull request by nikku**
Closes https://github.com/bpmn-io/form-js/issues/170

----

Look and feel demo:

capture LjAhCN_optimized

### CODE REVIEW

**Review by MaxTru — APPROVED** [review]

**Comment by nikku** [comment]
Note to design review: We currently work with a `54x54` icon grid in form-js land. 

Icon size shall be cleaned up / aligned once we migrate to the new properties panel infrastructure.

**Comment by andreasgeier** [comment]
Pleas use this updated icon in a 54x54 viewbox: https://github.com/camunda/camunda-modeler-design/blob/main/icons/entities/forms-54x54.svg?short_path=d53b419

**Comment by nikku** [comment]
> Pleas use this updated icon in a 54x54 viewbox: https://github.com/camunda/camunda-modeler-design/blob/main/icons/entities/forms-54x54.svg?short_path=d53b419

We're already using a scaled up version. Which visual effect would you like to accomplish?

**Comment by andreasgeier** [comment]
I quickly pasted the icon (32x32 size in a 54x54 viewbox) on a screenshot and this is the result:

Screen Shot 2021-09-15 at 10 04 35

Please check, your implementation seems to be different.

**Comment by nikku** [comment]
To properly integrate with our existing icons the form icon must be "54x54" in size on a "0 0 54 54" viewbox. We're doing some magic tricks to translate that image down to "36x36" dimensions in the panel.

This way it properly integrates with the [existing icons](https://github.com/bpmn-io/form-js/tree/master/packages/form-js-editor/src/render/components/palette/icons), for example [this one](https://github.com/bpmn-io/form-js/blob/master/packages/form-js-editor/src/render/components/palette/icons/Button.svg). To achieve the visual result you desire (https://github.com/bpmn-io/form-js/pull/172#issuecomment-919794464) the icon would need to have less padding.

### For Comparison

| your icon | existing icons |
| :--- | :--- |
| this is how your icon looks like | other icon another icon |

**Review by andreasgeier — APPROVED** [review]
I think the problem here is the "magic" of how this is implemented. In the future, we should avoid resizing the symbols outside of the canvas, otherwise, it doesn't make sense to provide pixel-sharp variants in different sizes.

I will accept your implementation as an intermediate step until we replaced this panel with the new one.

**Comment by nikku** [comment]
For further clarification, this is the space we have available: 

image

**Pull request merged**
