### PR TITLE
Editor Continued

### PR DESCRIPTION
**Pull request by philippfromme**
This PR adds the missing functionality for the initial release of the form editor.

What's inside?

* properties panel
* selection behavior
* basic drag and drop styling
* all features that are not yet supported have been unbuilt
* viewer and editor styles cleaned up (scoped, namespaced, ...)
* refactoring of field registry (viewer and editor have their own field registry, viewer has asynchronous registry corresponding to schema and data, editor has synchronous registry corresponding to schema only)

foo-compressed

### CODE REVIEW

**Comment by philippfromme** [comment]
@nikku Ready to be reviewed. 🦖

**Review by nikku — COMMENTED** [review]
Works on my machine.

**Review by nikku — APPROVED** [review]
Works on my machine :clap:

**Comment by philippfromme** [comment]
🚀

**Pull request merged**
