### PR TITLE
fix: prioritize adorner sizing

### LINKED ISSUE #598: Adorners cut off their text depending on window width
### Describe the Bug

You can't reliably use adorners, since they cut off their own text depending on the window width.

Bildschirmfoto 2023-04-12 um 19 43 52

Bildschirmfoto 2023-04-12 um 19 44 28

### Steps to Reproduce

1. Add a adorner (suffix or prefix) to a component
2. Resize the window
3. The adorner resizes, and likely hides it's text

### Expected Behavior

Adorners should always have prio compared with the content, i.e. the content can be cropped, but not the adorner (since the adorner provides important context information and can't be scrolled)

### Environment

- Recent form.js 0.14.0 / Tasklist 8.2.1

### PR DESCRIPTION
**Pull request by Skaiir**
Closes #598

### CODE REVIEW

**Review by vsgoulart — APPROVED** [review]

**Comment by pinussilvestrus** [comment]
Maybe let's create a demo and ask @RomanKostka and @christian-konrad for feedback, to avoid another back and forth with this 👍

**Comment by pinussilvestrus** [comment]
Demo can be found under: https://demo-598-prioritize-adorner-sp--camunda-form-playground.netlify.app/

**Review by RomanKostka — CHANGES_REQUESTED** [review]
way better!
i found two things:
1. the definition view of the input seems not behaving right. the input grows without being resized.  Not sure if this is by intention
image

2. nothing for this issue but something worth to mention again and again (as far as i know this is already tracked in another issue):
we should give our components a min-width to avoid things like this:
image

**Comment by Skaiir** [comment]
Both problems are present before and after the fix, so we're still merging this for the sake of iterative improvements. I will track the first in a new issue.

**Comment by Skaiir** [comment]
[1]: https://github.com/bpmn-io/form-js/issues/623
[2]: https://github.com/bpmn-io/form-js/issues/624

**Pull request merged**
