### PR TITLE
feat: simplify checklist icon

### PR DESCRIPTION
**Pull request by nikku**
Makes checklist icon more compact so it better fits into the existing context (palette + properties panel).

capture zqbE1j_optimized

### CODE REVIEW

**Comment by Skaiir** [comment]
I think it's a strict improvement but I'll wait on Roman for this one.

**Review by RomanKostka — CHANGES_REQUESTED** [review]
nice!
one thing i would like to add:
less stroke width for the checklist labels.
I created a new svg for that:
Checklist

**Comment by nikku** [comment]
Updated checklist icon. Works for me as well!

capture dg2P0Q_optimized

**Review by RomanKostka — APPROVED** [review]
thanks!
looks good from my point of view.

**Comment by nikku** [comment]
@Skaiir Awaiting your final review.

**Review by Skaiir — APPROVED** [review]

**Pull request merged**
