### PR TITLE
Add a basic form playground

### PR DESCRIPTION
**Pull request by nikku**
screenshot

Not sure if it is worth to have this as part of form-js. It is great for debugging the existing form though.

### CODE REVIEW

**Comment by philippfromme** [comment]
What's the status of this PR? It is still a draft.

**Comment by nikku** [comment]
Looking forward to engage in a discussion with you whether to have it as part of `form-js` or as an external library.

I'm fine with either.

**Comment by philippfromme** [comment]
> Looking forward to engage in a discussion with you whether to have it as part of `form-js` or as an external library.

Alright, let me check this out! 💻 🖱️

**Comment by philippfromme** [comment]
This is great! How do we plan to make this available? As an `npm` package? Deployed somewhere? As a GitHub repository?

**Comment by philippfromme** [comment]
We agreed to keep the playground as part of this repository for now. Thus, it can easily be consumed by `demo.bpmn.io`.

**Review by philippfromme — APPROVED** [review]
🚀

**Pull request merged**
