### PR TITLE
Allowing option values to be loaded from imported data

### LINKED ISSUE #197: Enable loading of values for all 'select-type' components via Form input data
__Is your feature request related to a problem? Please describe__

As part of our dynamic data loading initiative for our form components, we would want to enable users to drive their select-able data from sources other than the form schema.

As a starting point, we'll enable users to pass in the data themselves from outside the form via `form input data`, this first ticket handles that functionality. Following up to this will be allowing the configuration of the type of data source via the properties panel, as it is currently blocked by https://github.com/bpmn-io/form-js/issues/249.

__Describe the solution you'd like__

We want to support the rendering of 'select-type' component values via Input data, so that a form designer may dynamically build up these components. 

To this end, we'll need a few things:

- Create a differentiation in the schema for different data sources
- Allow our form components to interpret that differentiation and render appropriately
- Figure out how we want these dynamically driven form components to look in the preview when no data source is provided

___

SCHEMA EXAMPLE

**schema**
```js
{
  // values is ommited on purpose!
  //  "values": [
  //  {
  //   "label": "Value",
  //   "value": "value"
  //   }
  // ],
  "label": "Radio",
  "type": "radio",
  "id": "myRadio",
  "key": "radio",
  "valuesKey": "radioInputs"
}
```

**form data input**
```json
{
  "radio": "valA",
  "radioInputs": [
    {
      "label": "valA",
      "value": "valA"
    },
    {
      "label": "valB",
      "value": "valB"
    },
  ]
}
```

**Result**
Screenshot_20211108_203747

___

Implementation steps:
- [x] Agree on the final schema
- [x] Agree on UX for "empty" data, rendering nothing might be confusing to users
- [ ] Set up a whole new dynamic data form test case to work from
- [x] Enable components to be rendered dynamically
  - [x] Select
  - [x] Radio
  - [x] Checklist (depends on https://github.com/bpmn-io/form-js/pull/255)
  - [x] Taglist (depends on https://github.com/bpmn-io/form-js/issues/198)
- [x] Implement "empty" data solution

__Describe alternatives you've considered__

n/a

__Additional context__

Requires https://github.com/bpmn-io/form-js/issues/196
Raised during discussion of https://jira.camunda.com/browse/SUPPORT-12025
Also requested via https://jira.camunda.com/browse/SUPPORT-12306
Child of https://github.com/bpmn-io/form-js/issues/200

### PR DESCRIPTION
**Pull request by dfulgham**
* Adding OptionsFromKeyEntry to GeneralGroup
* added optionFromKey:boolean, optionsKey:string field properties to allow select and radio to load their options form imported data.
* updated importer to import initialData for keys used by selects and radios
* Also refactored playground submit data to properly filter to only fields that are present.

Implements and closes #197

### CODE REVIEW

**Comment by MaxTru** [comment]
Thanks for this PR.

This looks solid and is from the first look a good implementation of #197.

We have the overall story of "supporting dynamic forms" on our roadmap for Q2 and would like to consider this PR here as part of that excercise. So please understand that we really appreciate this groundwork, but cannot merge as of now. I will leave it open and keep it in the backlog.

In the meantime: 
If you need this component for your particular use case, I think it would still make a lot of sense to look into https://github.com/bpmn-io/form-js/issues/123, so that this could be plugged-in, even if it was not part of the core form-js library.

**Comment by pinussilvestrus** [comment]
Hi @dfulgham, a small update from our side: We plan to work on this topic this quarter and I will likely use this pull request as a starting point!

I will use [the referenced issue](https://github.com/bpmn-io/form-js/issues/197) to keep things up to date 👍

**Comment by dfulgham** [comment]
@pinussilvestrus thats great news, sorry been away for a bit moving geographically.  I would like to work on this project a lot more, any chance of getting a little more integrated in this project?

One of the items I want to get working on a little more is the custom components pieces, like the file upload and star rating components I created in one of my forks.

**Comment by nikku** [comment]
@dfulgham Happy to work with you on form-js to improve it for the better.

Making the toolkit pluggable and also whitelisting components is one thing we're not working on right now, but you did a tremendous amount of work.

I#d love to help you to shape these things up and get them into our codebase (https://github.com/bpmn-io/form-js/pull/239#issuecomment-1122166836).

At the same time we're working on dynamic form values right now (https://github.com/bpmn-io/form-js/issues/197), not dependent, but also exciting. Glad you also jumped in to share your feedback from the integrators perspective.

**Comment by nikku** [comment]
You can track what we're working on in form land [via our task board, too](https://tasks.bpmn.io/board?c=%21Done%2C%21Inbox&s=repo%3Abpmn-io%2Fform-js).

**Comment by Skaiir** [comment]
Closed in favor of https://github.com/bpmn-io/form-js/pull/270, thank you for the contribution we inspired ourselves from this work.

**Pull request closed without merging**
