### PR TITLE
fix(tsc): copy types flat

### LINKED ISSUE #529: Can't use Typescript types due to wrong packaging
### Describe the Bug

I'm trying to use form-js in an Angular project, but it seems that the files aren't correctly packaged. 

I'm seeing the following issues:

```
...
Error: ../node_modules/@bpmn-io/form-js-viewer/dist/types/Form.d.ts:127:31 - error TS2307: Cannot find module './types' or its corresponding type declarations.

127 export type Injector = import('./types').Injector;
                                  ~~~~~~~~~


Error: ../node_modules/@bpmn-io/form-js-viewer/dist/types/Form.d.ts:128:27 - error TS2307: Cannot find module './types' or its corresponding type declarations.

128 export type Data = import('./types').Data;
                              ~~~~~~~~~


Error: ../node_modules/@bpmn-io/form-js-viewer/dist/types/Form.d.ts:129:29 - error TS2307: Cannot find module './types' or its corresponding type declarations.

129 export type Errors = import('./types').Errors;
                                ~~~~~~~~~


Error: ../node_modules/@bpmn-io/form-js-viewer/dist/types/Form.d.ts:130:29 - error TS2307: Cannot find module './types' or its corresponding type declarations.

130 export type Schema = import('./types').Schema;
                                ~~~~~~~~~
...
```

Part of Form.d.ts
```
...
export type Injector = import('./types').Injector;
export type Data = import('./types').Data;
export type Errors = import('./types').Errors;
export type Schema = import('./types').Schema;
export type FormProperties = import('./types').FormProperties;
export type FormProperty = import('./types').FormProperty;
export type FormEvent = import('./types').FormEvent;
export type FormOptions = import('./types').FormOptions;
...
```

So it seems that the file `@bpmn-io/form-js-viewer/dist/types/Form.d.ts` is trying to read the file `types` in the current directory, but the actual `types.d.ts` file is still in the `src/` subfolder.

```
.
├── dist
│   ├── assets
│   │   ├── flatpickr
│   │   │   └── light.css
│   │   └── form-js.css
│   ├── index.cjs
│   ├── index.cjs.map
│   ├── index.es.js
│   ├── index.es.js.map
│   └── types
│       ├── core
│       │   └── ...
│       ├── import
│       │   └── ...
│       ├── render
│       │   └── ...
│       ├── src
│       │   └── types.d.ts
│       └── util
│       │   └── ...
│       ├── Form.d.ts
│       ├── index.d.ts
├── LICENSE
├── package.json
└── README.md
```

### Steps to Reproduce

1. npm install @bpmn-io/form-js-viewer
2. Add `import {Form} from '@bpmn-io/form-js-viewer';` on a typescript file.
2. Try to compile in an typescript project
3. It's complaining that the file `types` can't be found.

I think it's related to https://github.com/bpmn-io/form-js/pull/143.

### Environment

- Host: Node v16.17.1 / Angular 12
- OS: Ubuntu 22.04
- Library version: 0.11.0

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #529

* fixes missing external types
* execute type integration test
* refactor `iconsByType` to a helper function

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
I continued the efforts from https://github.com/bpmn-io/form-js/pull/143 to execute the `tsc` checks against our exports. Missing errors we'd need to resolve
* [`iconsByType`](https://github.com/bpmn-io/form-js/blob/develop/packages/form-js-viewer/src/render/components/icons/index.js): Cannot find name "..."
* unrelated errors from used libraries? E.g. 

> Error: ../../node_modules/@types/sinon/index.d.ts(780,39): error TS2694: Namespace '"/home/runner/work/form-js/form-js/node_modules/@sinonjs/fake-timers/types/fake-timers-src"' has no exported member 'InstalledMethods'.

**Comment by shadouuw** [comment]
i found a solution some svg files are missing and there is another problem in form.d.ts if you want i can share my node_module

**Comment by pinussilvestrus** [comment]
@shadouuw I'm happy to review a PR or any other hint for improving the situation 👍 Feel free to share; we are appreciating this 👍

**Comment by pinussilvestrus** [comment]
@vsgoulart @Skaiir after a bit back-and-forth I decided to resolve the missing icon types by refactoring the `iconsByTpe` to a helper function. It seems like typescript has difficulties resolving svg icons as types, so this is a small workaround.

Let me know what you think. All other type errors are resolved (cf. integration test).

**Comment by pinussilvestrus** [comment]
> @pinussilvestrus This isn't surprising, the SVG resolution is a rollup plugin. No surprise tsc can't do it.

There might be workarounds though which I had a look at (https://gist.github.com/raqystyle/2063bb40bfe707296e9c0790d86c2877). However, I wouldn't want too much magic in our build pipeline.

**Comment by Skaiir** [comment]
> However, I wouldn't want too much magic in our build pipeline.

Agreed, it's magicky enough as it stands with our bundler and type generator being separate tools :trollface:

**Review by Skaiir — APPROVED** [review]
Looks great to me :D

**Review by vsgoulart — APPROVED** [review]

**Pull request merged**
