### PR TITLE
Make Options Optional

### PR DESCRIPTION
**Pull request by philippfromme**
Instantiating a form or form editor without the `options` argument would blow up even though we consider them optional.

```javascript
const form = new Form();
```

doesn't 💥 up anymore.

### CODE REVIEW

**Review by nikku — CHANGES_REQUESTED** [review]
Can we haz test cases for this usage pattern?

Otherwise :boom:

**Comment by philippfromme** [comment]
Added tests to ensure it don't go 💥.

**Review by nikku — APPROVED** [review]
Good one :clap:.

Removing `schemaVersion` from the editor is a good find, too. Let's assume no-one is using it yet (and no one should).

**Comment by philippfromme** [comment]
> Let's assume no-one is using it yet (and no one should).

🤞🏻

**Pull request merged**
