### PR TITLE
fix(viewer): required fields must not be empty string

### LINKED ISSUE #114: Field validation not running on required fields
__Describe the Bug__
On v0.2.3 when you delete the value of a required field the error doesn't appear.
This appears to be happening only on fields that are only required, fields that are required and have a pattern validation seem to be working as expected.

__Steps to Reproduce__

On this [Codesandbox using v0.2.3](https://codesandbox.io/s/new-form-js-k21jr?file=/src/App.js)

1. Delete the value of the field `Creditor`
2. No error appears

If you do the same on the [old version](https://codesandbox.io/s/old-form-js-scbc9?file=/src/App.js) we see the error

__Expected Behavior__

An error should appear saying that the field is required

### PR DESCRIPTION
**Pull request by philippfromme**
Closes #114

### CODE REVIEW

**Comment by nikku** [comment]
Can we make tests `text:` not `chore:` in the commit message?

**Comment by philippfromme** [comment]
> Can we make tests `text:` not `chore:` in the commit message?

Should I use `tests:`?

**Comment by philippfromme** [comment]
@nikku, changed the commit message to `test: add integration test for validation errors`.

**Review by nikku — APPROVED** [review]
:drum:

**Pull request merged**
