### PR TITLE
add default value in form Item

### PR DESCRIPTION
**Pull request by Fredxingxing**
hello 

this PR is closing #191 .

### CODE REVIEW

**Comment by nikku** [comment]
Thanks for this PR, I think it is a good start.

May I ask why you decided to make `required` and `defaultValue` two dependent features? I believe both shall be independent (i.e. there is a pre-filled value in a field and I still may remove it, ending up to submit an empty (or null) value.

**Comment by Fredxingxing** [comment]
hi @nikku,

I make two dependent features just for figour out #190 that situation,  not think universality,  i may go wrong. 😂

the elaboration is making a input for users fill defaultValue to form data, and have no connection with require, so the place of the input should be General Panel not in Validate Panel, am i right?

**Comment by nikku** [comment]
> the elaboration is making a input for users fill defaultValue to form data, and have no connection with require, so the place of the input should be General Panel not in Validate Panel, am i right?

You're right; I'd like to have both features separately.

**Comment by Fredxingxing** [comment]
> > the elaboration is making a input for users fill defaultValue to form data, and have no connection with require, so the place of the input should be General Panel not in Validate Panel, am i right?
> 
> You're right; I'd like to have both features separately.

ok

**Comment by Fredxingxing** [comment]
this PR is closing #191 

add defaultValue input in editor panel

**Comment by nikku** [comment]
Thanks for your follow-up. I'll look into this next week.

**Comment by MaxTru** [comment]
> Thanks for your follow-up. I'll look into this next week.

@nikku can you please give a status update? Should someone else jump in?

**Comment by nikku** [comment]
@MaxTru Maybe someone else can jump onto this one. I don't have the capacity at the moment.

**Comment by nikku** [comment]
@Fredxingxing My sincere appologies for leaving this PR hanging for way too long. And thanks for @philippfromme for taking it over.

**Comment by Fredxingxing** [comment]
> @Fredxingxing My sincere appologies for leaving this PR hanging for way too long. And thanks for @philippfromme for taking it over.

it's doesn't matter, have a good day ~

**Comment by philippfromme** [comment]
I'm closing this PR in favor of https://github.com/bpmn-io/form-js/pull/213. I've incorporated your changes, @Fredxingxing, but had to undo most of them since the feature wasn't working as expected. Furthermore, the feature wasn't tested.

For your next contribution please ensure that

* the pull request has all the necessary information
* the feature works and is tested

Putting yourself in the shoes of the reviewer can be helpful.

Thanks for your contribution. 👍🏻

**Comment by Fredxingxing** [comment]
> I'm closing this PR in favor of #213. I've incorporated your changes, @Fredxingxing, but had to undo most of them since the feature wasn't working as expected. Furthermore, the feature wasn't tested.
> 
> For your next contribution please ensure that
> 
> * the pull request has all the necessary information
> * the feature works and is tested
> 
> Putting yourself in the shoes of the reviewer can be helpful.
> 
> Thanks for your contribution. 👍🏻

thx ur suggestions.🥤

i'll ensure my PR work and test and have full scope in next contribution.

**Pull request closed without merging**
