### PR TITLE
chore(CHANGELOG): update to v0.7.0

### PR DESCRIPTION
**Pull request by smbea**

### CODE REVIEW

**Comment by MaxTru** [comment]
Could @philippfromme or @nikku please take a look and confirm we are okay with 0.7.0?

**Comment by nikku** [comment]
Absolutely fine.

**Comment by nikku** [comment]
Or wait for more features to arrive. Like fixing the bug on radio?

**Comment by MaxTru** [comment]
Let's please have it ASAP. So @smbea if you fix the bug on radio buttons soon, we can do that. But let's not "just wait". 

Reason: Platform needs to integrate this into cockpit for 7.17 (so that we have cockpit tasklist up to date for April release)

**Comment by smbea** [comment]
Should be simple, I'll work on it. If I see it's stalling the release, then we can go ahead without it.

**Comment by MaxTru** [comment]
Converted to draft until https://github.com/bpmn-io/form-js/pull/228#issuecomment-1042980595 is done

**Comment by smbea** [comment]
I had missed that one. Added now

**Review by MaxTru — APPROVED** [review]

**Pull request merged**
