### PR TITLE
feat: normalized font and misc styling form-wide

### LINKED ISSUE #506: Establish rules for fonts within input fields and apply consistently.
### What should we do?

Currently, there is a discrepancy between fonts within inputs and fonts in the general UI. Fonts in inputs are sized to 13.3333px while fonts outside of it are sized to 14px. There are also some further inconsistencies in terms of disabled font color, and styling of fonts in these states. Styling of placeholders, etc. 

Let's carry out a discussion on what we want these things to look like, establish some rules and clean up across all components. The implementation itself should be rather trivial, but there's certainly some back and forth that can occur in terms of decision-making.  

For reference here is what an input field looks like currently at 13+1/3px
image

And how it would look with a 14px font size
image

### Why should we do it?

To offer a consistent UX across components, and if relevant in this scenario to keep the readability of our components high (a11y)

### PR DESCRIPTION
**Pull request by Skaiir**
Closes #506

This ended up becoming a bit larger than just the fonts.

### CODE REVIEW

**Comment by Skaiir** [comment]
Will provide a preview in a bit @RomanKostka

**Comment by Skaiir** [comment]
Preview available here: https://demo-506-font-styling-normalization--camunda-form-playground.netlify.app/

**Review by RomanKostka — APPROVED** [review]
nice, thanks!
looks great from my point of view.

**Review by vsgoulart — APPROVED** [review]
Looks great, thanks for the effort

**Comment by vsgoulart** [comment]
@Skaiir it seems have failing tests

**Pull request merged**
