### PR TITLE
feat: add mac and windows CI checks

### LINKED ISSUE #312: Add windows and mac CI checks
__Is your feature request related to a problem? Please describe__

When I encounter a CI bug on Windows locally I cannot tell if it is due to a local problem or something else broke it. Just to improve dev experience and to cover all cases, we should also run form-js through windows and mac CI.

__Describe the solution you'd like__

Using GHW, we should pass form-js through CI and on both windows and mac and not only linux.

__Describe alternatives you've considered__

n/a

### PR DESCRIPTION
**Pull request by Skaiir**
Closes #312

### CODE REVIEW

**Comment by nikku** [comment]
Why would we want to do that? What additional insights do we expect to gain?

**Comment by Skaiir** [comment]
@nikku When I am developing on Windows and I come across an error during a build, it's completely unclear to me if this is a me issue or if a previous change from someone else caused them. With CI, I can safely know that it's going to be on my end. This change forces us to support windows development and will avoid us accidentally breaking development for these other OSes, an issue which I've encountered many times across some of our linux-only CI repos.

**Comment by nikku** [comment]
Fair enough! :)

**Review by nikku — APPROVED** [review]
Good change! :heart: :window:

**Pull request merged**
