### PR TITLE
Integrate Feel Popup Editor

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Related to https://github.com/camunda/team-hto/issues/262

Demo available via: https://demo-popup-editor-demo--camunda-form-playground.netlify.app/

What's included
* Open up a popup editor for FEEL expressions and FEELERS templates
* Live editing in the preview
* Dragging support

image

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Apparently the popup is crashing in form-playground. I will have to investigate this.

**Comment by pinussilvestrus** [comment]
For transparency, feedback shared from @christian-konrad: https://camunda.slack.com/archives/C046XS3GGCR/p1689154971847169?thread_ts=1689153918.296359&cid=C046XS3GGCR

**Comment by pinussilvestrus** [comment]
@Skaiir This is ready for review now. As we already had a proper review in the properties panel, this should be fine to go, unless you see major blockers.

**Comment by Skaiir** [comment]
LGTM 👍

**Review by Skaiir — APPROVED** [review]

**Pull request merged**
