### PR TITLE
feat: Add Carbon compatibility styles

### LINKED ISSUE #936: Carbonise new table component

### PR DESCRIPTION
**Pull request by vsgoulart**
Closes #936

- [ ] This PR adds a new `form-js` element or visually changes an existing component.
  * => In that case, we need to ensure we follow up on this, e.g. by [creating an issue in Tasklist](https://github.com/camunda/tasklist/issues/new/choose)

### CODE REVIEW

**Comment by vsgoulart** [comment]
Some preview

image
image

**Review by Skaiir — APPROVED** [review]
Looks good, as a follow up it would be good to bring a table into the example test cases so that they can easily be seen via `npm run start:carbon` (and also trigger our regression tests)

Maybe we could do this after https://github.com/bpmn-io/form-js/issues/942

**Comment by Skaiir** [comment]
Ah only one thing missing I see actually, can you change the commit message to reference the base issue?

**Comment by vsgoulart** [comment]
> Ah only one thing missing I see actually, can you change the commit message to reference the base issue?
> 
> We usually write `Related to #___` or `Closes #___`

I don't think it makes sense to link to the root issue if we have a split issue. The issue I linked is also linked to the root issue.

**Pull request merged**
