### PR TITLE
fix: palette style improvements

### LINKED ISSUE #539: Wrong Palette Padding on Smaller Screens Due to Scroll Bar
### Describe the Bug

Just a minor issue, but on smaller screens, the padding in the palette looks wrong due to the scroll bar that isn't accounted for.

Smaller Screen

image

Larger Screen

image

### Steps to Reproduce

1. Use a smaller screen
2. Scroll bar appears in palette
3. Padding is wrong

### Expected Behavior

Padding accounts for scroll bar.

### Environment

- Library version: 0.12.1

### LINKED ISSUE #848: Improve palette visuals
### Describe the Bug

Not so much of a bug, but the palette has a bit of a strange visual design, as its contrast reduces on hover, which is a bit counter intuitive in terms of visuals. 

### Steps to Reproduce

1. Hover over palette entry
2. Palette entry grays out, which isn't ideal

grafik

### Expected Behavior

We should if anything increase the contrast here. An outline might be the solution. 

grafik

### PR DESCRIPTION
**Pull request by Skaiir**
Closes #848
Closes #539

Improved the alignment of palette elements when scrollbar is visible, changed the focus to an outline instead of a margin to prevent blinking. Gave elements a small outline to make them pop. Made hover state also an outline. Compressed the palette a tiny bit.

### CODE REVIEW

**Comment by Skaiir** [comment]
@volodymyr-melnykc Currently deploying a preview. Let us know what you think :)

**Comment by Skaiir** [comment]
Huh the deployments are failing. @pinussilvestrus any idea what this be?

**Comment by pinussilvestrus** [comment]
@Skaiir it seems like there are currently general outages with some GitHub actions + using git functions, cf. https://github.com/camunda/tasklist/actions/runs/6563544478/job/17828023329

Seems unrelated to this PR.

**Review by vsgoulart — APPROVED** [review]

**Comment by pinussilvestrus** [comment]
@vsgoulart that's true! I requested to update it.

image

**Pull request merged**
