### PR TITLE
feat: bootstrap document preview element

### PR DESCRIPTION
**Pull request by vsgoulart**
This PR bootstraps the new new `Document preview` element. It adds the new component to the palette, updates the JSON schema definition and sets up the the properties panel for it.

The next PR will include the component runtime logic.

Related to #1327

- [x] This PR adds a new `form-js` element or visually changes an existing component.
  - => In that case, we need to ensure we follow up on this, e.g. by [creating an issue in Tasklist](https://github.com/camunda/tasklist/issues/new/choose)

### CODE REVIEW

**Comment by vsgoulart** [comment]
@barmac @nikku Could you or someone from the modelling team help with code reviews since we're a bit short staffed on the HTO team?

**Comment by nikku** [comment]
@vsgoulart I'll hopefully get to this PR tomorrow :crossed_fingers:

**Review by nikku — COMMENTED** [review]
Technical feedback:

* From the looks of it this feature integrates nicely with the way other features (components) are built
  * Integrates with editor, viewer + schema
  * Built in the "standard" way
  * Schema version bumped
* I see a lack of test coverage on the editor, i.e. don't see where we verify this works properly (configuration yields right form schema)
  * :arrow_right: At this point I assume you tested the E2E workings manually, rigidly.
* No test coverage in the viewer
  * :arrow_right: At this point I assume you tested the E2E workings manually, rigidly.
  
UI / UX feedback:

I verified if this works in the playground via

```
npm run start form-playground
```

* It seems not to be properly integrated, I can pull it in, but don't see an (editor) preview, I don't see a viewer preview either:

image

**Comment by nikku** [comment]
I ask @Skaiir to also have a look, as you are a more knowledgable person in the realm of `form-*`.

**Comment by vsgoulart** [comment]
@nikku This is just the first half of the feature to make it easier to review. For now it's just the modelling part and then the next PR will have the runtime implementation on a second PR.

That's why I'm targeting a feature branch too instead of develop too

**Review by Skaiir — APPROVED** [review]
One small thing, we don't need a new `title` there is already a way to change the name of the label property based on file types.

See `function getLabelText(type)`

Aside from that, great work :rocket:

**Comment by vsgoulart** [comment]
Custom `title` schema prop was removed via the last the commit

**Pull request merged**
