### PR TITLE
chore: lint:types editor source

### PR DESCRIPTION
**Pull request by nikku**
This surfaced a few places where we can improve the code base.

[A few issues remain](https://github.com/bpmn-io/form-js/runs/2713020035?check_suite_focus=true#step:6:81) that honestly look like plain bugs to me.

### CODE REVIEW

**Comment by nikku** [comment]
@philippfromme Could you double check if the detected issues are

**Comment by philippfromme** [comment]
Should be fixed now.

**Review by philippfromme — APPROVED** [review]
Let's go ahead and merge this. 🥇

**Comment by nikku** [comment]
I like :clap:

**Pull request merged**
